---
title: "data_exploration"
author: "Isabel and Eric"
date: "12/17/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#pkgs <- c("factoextra",  "NbClust")
#install.packages(pkgs)
#install.packages("mclust")
```


```{r}
library(tidyverse)
library(plyr)
library(dplyr)
library(mclust)
library(factoextra)
library(NbClust)
```

```{r read-in}
svi <- read.csv("Datasets/SVI2018_US_COUNTY.csv")

#sahie <- read.csv("Datasets/SAHIE_Manipulated.csv")

#deaths <- read.csv("Datasets/covid_deaths_usafacts.csv")

pop <- read_csv("Datasets/covid_county_population_usafacts.csv")
#case_count <- read_csv("Datasets/covid_confirmed_usafacts.csv")
```


```{r}
#just reading in covid data from enviornment 
#run data_manipulation.Rmd to update covid data with api 

cv2 <- read_csv("Datasets/covid_data.csv")
cv2 <- cv2[c(1, 2, 4)]
#fix later
names(cv2)[1] <- "FIPS"
#add covid data to SVI
svi <- merge(cv2, svi, by='FIPS') 
#add population
pop <- pop[-c(2,3)]
names(pop)[1] <- "FIPS"

svi <- merge(pop, svi, by='FIPS') 


```


```{r}
#adjust covid totals to ratios of population
svi$case_by_pop <- svi$total_cases / svi$population *10000
svi$death_by_pop <- svi$total_death / svi$population *10000
```

```{r}


```

```{r}

#print(cor(svi_covid$case_by_pop, svi_covid))
#print("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
#print(cor(svi_covid$death_by_pop, svi_covid))

#drop none numeric columns (county/state names)
svi_temp <- svi[-c(6:9)]

case_svi_cor <- cor(svi_temp$case_by_pop, svi_temp)
high_case_svi_i <- which(case_svi_cor>=0.1)
print(case_svi_cor[high_case_svi_i])
print(colnames(svi_temp)[high_case_svi_i])#need to include the variable names 


death_svi_cor <- cor(svi_temp$death_by_pop, svi_temp)
high_death_svi_i <- which(death_svi_cor>=0.1)
print(death_svi_cor[high_death_svi_i])
print(colnames(svi_temp)[high_death_svi_i])#need to include the variable names 

```
```{r}
#drop margins of error 

#colnames(svi_temp)

svi_temp <- svi_temp[, grep('^EP', colnames(svi_temp)) ]
colnames(svi_temp)
```



```{r}
fviz_nbclust(svi_temp, FUN = hcut, method = "wss")
fviz_nbclust(svi_temp, FUN = hcut, method = "silhouette")


```

```{r}
#ward hierarchical clustering 
#just thrwoing shit at the wall and seeing what sticks

d <- dist(svi_temp, method = "euclidean") #translate data to distance
fit <- hclust(d, method = "ward.D2")
plot(fit, cex = 0.6, hang = -1)
groups <- cutree(fit, k = 3)

table(groups)
#plot.new()
#rect.hclust(fit, k=5, border="red")
```

```{r}
fviz_cluster(list(data = svi_temp, cluster = groups))
```


```{r}
fviz_nbclust(svi_temp, FUN = hcut, method = "wss")

#ward hierarchical clustering 
#just thrwoing shit at the wall and seeing what sticks

d <- dist(svi_temp, method = "euclidean") #translate data to distance
fit <- hclust(d, method = "complete")
plot(fit)
groups <- cutree(fit, k = 3)

table(groups)
#plot.new()
#rect.hclust(fit, k=5, border="red")


```

```{r}
library(cluster)
hc_a <- agnes(svi_temp, method = "ward")
groups <- cutree(as.hclust(hc_a), k = 3)

table(groups)
hc_a$ac

fviz_cluster(list(data = svi_temp, cluster = groups))

```

```{r}
# Cut diana() tree into 4 groups
hc_d <- diana(svi_temp)
groups <- cutree(as.hclust(hc_d), k = 3)

table(groups)
hc_d$dc
```

