---
title: "Data_Manipulation"
author: "Isabel and Eric"
date: "12/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r}
library(plyr)
library(tidyverse)
```


```{r}

base_dat <- read_csv('Datasets/19estimates_counties.csv')

clist <- split(base_dat, base_dat$GEOID)

```

```{r}
foo <- as.data.frame(t(clist[[1]]))

#remove columns without data 
countyA_dat <- foo[-c(1, 2, 3, 17, 20, 23, 24, 32, 33, 40, 47, 48, 56, 57, 65, 69, 70, 77, 78, 87, 90, 91, 94, 95, 98, 101, 104, 107, 108, 117, 118, 126, 127, 131, 132, 134, 138, 142, 143, 151, 152, 165, 166, 195, 196)]
#there is a better way to do this - maybe if question number isnt a whole number

#remove rows with all NAs 
not_all_na <- function(x) any(!is.na(x))

countyA_dat <- na_if(countyA_dat, "(X)")
countyA_dat %>% select_if(not_all_na) #I cant tell if this is working or not

```

```{r}
clean_county <- function(county_df){
  t_county <- as.data.frame(t(county_df))
  county_dat <- t_county[-c(1, 2, 3, 17, 20, 23, 24, 32, 33, 40, 47, 48, 56, 57, 65, 69, 70, 77, 78, 87, 90, 91, 94, 95, 98, 101, 104, 107, 108, 117, 118, 126, 127, 131, 132, 134, 138, 142, 143, 151, 152, 165, 166, 195, 196)]
  not_all_na <- function(x) any(!is.na(x))

  county_dat <- na_if(county_dat, "(X)")
  county_dat <- county_dat %>% select_if(not_all_na)
  #rename cols 
  names(county_dat) <- county_dat[6,]


  return(county_dat)
}
  
```

```{r}

new_tib_list <- lapply(clist, clean_county)
```

```{r}
add_loc_cols <- function(county_dat){
  county_dat$TableID  <- rep(county_dat[1:3, 1][1], length(county_dat$Spouse))
  county_dat$GeoID <- rep(county_dat[1:3, 1][2], length(county_dat$Spouse))
  county_dat$GeoName <- rep(county_dat[1:3, 1][3], length(county_dat$Spouse))
  county_dat <- county_dat[-c(1, 2, 3, 4, s6), ]
  return(county_dat)
}

tiblist <- lapply(new_tib_list, add_loc_cols)

tiblist[[1]]

```

```{r}
CompleteEstimates <- bind_rows(tiblist)

write_csv(CompleteEstimates, 'Datasets/estiamtes19_v2.csv')
```

```{r}
acs <- read.csv('Datasets/estiamtes19_v2.csv')
num_county <- unique(acs['GeoName'])
print(unique(acs['GeoName']))
```


```{r}
# library (readr)
 # 
 # cv.ny<-read.csv(url("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"))
```



