---
title: "week10"
author: "Isabel and Eric"
date: "3/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#install.packages("naniar")
library(tidyverse)
library(naniar)
library(factoextra)
library(cluster)
```

```{r}
#start putting together prettier script 
#read in 
#Social Vunerability Index
svi <- read.csv("Datasets/SVI2018_US_COUNTY.csv")

#drop none numeric columns (county/state names)
svi_temp <- svi[-c(6:9)]
#drop margins of error 
#colnames(svi_temp)
svi_temp <- svi_temp[, grep('^EP', colnames(svi_temp)) ]
svi_temp$FIPS <- svi$FIPS
colnames(svi_temp)

svi_temp <- svi_temp %>% replace_with_na_all(condition = ~.x == -999) #converts -999 to na
print(dim(svi_temp))
svi_temp <- svi_temp %>% drop_na()  #drops NA - only lose one county 
print(dim(svi_temp))

```

```{r}
#get ideal number of clusters 
fviz_nbclust(svi_temp, FUN = hcut, method = "wss")
fviz_nbclust(svi_temp, FUN = hcut, method = "silhouette")

```


```{r}
#ward hierarchical clustering 

d <- dist(svi_temp, method = "euclidean") #translate data to distance
fit <- hclust(d, method = "ward.D2")
plot(fit, cex = 0.6, hang = -1)
groups_w <- cutree(fit, k = 3)

table(groups_w)
#plot.new()
#rect.hclust(fit, k=5, border="red")
```




```{r}
fviz_cluster(list(data = svi_temp, cluster = groups_w))
```


```{r}
fviz_nbclust(svi_temp, FUN = hcut, method = "wss")

#complete hierarchical clustering 
#just thrwoing shit at the wall and seeing what sticks

d <- dist(svi_temp, method = "euclidean") #translate data to distance
fit <- hclust(d, method = "complete")
plot(fit)
groups_c <- cutree(fit, k = 3)

table(groups_c)
#plot.new()
#rect.hclust(fit, k=5, border="red")

fviz_cluster(list(data = svi_temp, cluster = groups_c))


```

```{r}
#agglomerative nesting 
#agnes clustering 
library(cluster)
hc_a <- agnes(svi_temp, method = "average")
groups_a <- cutree(as.hclust(hc_a), k = 3)

table(groups_a)
hc_a$ac

fviz_cluster(list(data = svi_temp, cluster = groups_a))

```



```{r}
#diana clustering

# Cut diana() tree into 
hc_d <- diana(svi_temp)
groups_d <- cutree(as.hclust(hc_d), k = 3)

table(groups_d)
hc_d$dc

fviz_cluster(list(data = svi_temp, cluster = groups_d))

```


```{r}
#add clusters to new dataframe 
svi_temp$cluster_ward = groups_w
svi_temp$cluster_complete = groups_c
svi_temp$cluster_agnes = groups_a
svi_temp$cluster_diana = groups_d


table(groups_w)
table(groups_c)
table(groups_a)
table(groups_d)

#add in population and 
pop <- as_tibble(cbind(svi$FIPS, svi$E_TOTPOP))

#get updated covid data
library (readr)
cv<-read.csv(url("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"))

#drop date bc we want aggregation
cv <- cv[-c(1)]

total_cases <- aggregate(cv$cases, by=list(fips=cv$fips), FUN=sum)
total_death <- aggregate(cv$deaths, by=list(fips=cv$fips), FUN = sum)

cv2 <- cbind(total_cases, total_death)
names(cv2) <- c("fips", "total_cases", "fips", "total_death")
write_csv(cv2, 'Datasets/covid_data.csv')


cv2 <- read_csv("Datasets/covid_data.csv")
cv2 <- cv2[c(1, 2, 4)]
#fix later
names(cv2) <- c("FIPS", "total_cases", "total_death")

#add covid data to SVI
svi_temp <- merge(cv2, svi_temp, by='FIPS') 

#add population
names(pop) <- c("FIPS", "population")

svi_temp <- merge(pop, svi_temp, by='FIPS') 


#adjust covid totals to ratios of population
svi_temp$case_by_pop <- svi_temp$total_cases / svi_temp$population
svi_temp$death_by_pop <- svi_temp$total_death / svi_temp$population
```


```{r}

```


```{r}
ward <- aggregate(svi_clust, list(svi_clust$cluster_ward), mean)
ward
```

```{r}
completeclust <- aggregate(svi_clust, list(svi_clust$cluster_complete), mean)
completeclust
```


```{r}
agnes <- aggregate(svi_clust, list(svi_clust$cluster_agnes), mean)
agnes
```


```{r}
diana <- aggregate(svi_clust, list(svi_clust$cluster_diana), mean)
diana
```

# Cluster Evaluation
```{r}
#base level prediction 
noclust <- select(svi_temp, -c(cluster_diana, cluster_agnes, cluster_complete, cluster_ward))
base_model <- glm(case_by_pop ~ ., data=svi_temp)
summary(base_model)

print(with(summary(base_model), 1 - deviance/null.deviance))
```

```{r}
#ward evaluate 
ward_dat <- select(svi_temp, -c(cluster_diana, cluster_agnes, cluster_complete))
#ward_1 <- subset(ward_dat, cluster_ward==1)
ward_model <- glm(case_by_pop ~ ., data=ward_dat)
summary(ward_model)

print(with(summary(ward_model), 1 - deviance/null.deviance))
```
```{r}
#complete evaluate 
complete_dat <- select(svi_temp, -c(cluster_diana, cluster_agnes, cluster_ward))
#ward_1 <- subset(ward_dat, cluster_ward==1)
complete_model <- glm(case_by_pop ~ ., data=complete_dat)
summary(complete_model)

print(with(summary(complete_model), 1 - deviance/null.deviance))
```

```{r}
#agnes evaluate 
agnes_dat <- select(svi_temp, -c(cluster_diana, cluster_complete, cluster_ward))
#ward_1 <- subset(ward_dat, cluster_ward==1)
agnes_model <- glm(case_by_pop ~ ., data=agnes_dat)
summary(agnes_model)

print(with(summary(agnes_model), 1 - deviance/null.deviance))
```

```{r}
#diana evaluate 
diana_dat <- select(svi_temp, -c(cluster_agnes, cluster_complete, cluster_ward))
#ward_1 <- subset(ward_dat, cluster_ward==1)
diana_model <- glm(case_by_pop ~ ., data=diana_dat)
summary(diana_model)

print(with(summary(diana_model), 1 - deviance/null.deviance))
```


